config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :mentors do
    resources :reviews
    resources :reservations
  end

  root 'pages#home'
  get 'about' => 'pages#about'
  get 'bementor' => 'pages#bementor'
  get 'dashboard' => 'pages#dashboard'
  post '/call/:id', to:'transactions#create', as: :call
  get '/pickup/:guid', to:'transactions#pickup', as: :pickup 

end

app/models/mentor.rb
class Mentor < ActiveRecord::Base
	

	belongs_to :user

	has_many :sales

	has_many :reviews

 	has_many :reservations

	has_attached_file :cover, styles: { medium: "300x300>", thumb: "100x100>" }
  	validates_attachment_content_type :cover, content_type: /\Aimage\/.*\z/

	validates :name, :profession, :location, :description, :price, :industries, :expertise, :company, presence: true
	validates :price, numericality: { greater_than: 0.49 }
	validates :cover, attachment_presence: true

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :user
  belongs_to :mentor
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user
	belongs_to :mentor
end

app/models/sale.rb
class Sale < ActiveRecord::Base
	before_create :generate_guid
	belongs_to :mentor
	
	include AASM
	aasm column: 'state' do
	    state :sleeping, :initial => true
	    state :running, :completed
	    state :errored

	    event :running, after: :charge_card do
	    	transitions from: :sleeping, to: :running
    	end
    	
    	event :complete do
    		transitions from: :running, to: :completed
		end

		event :fail do
			transitions from: :running, to: :errored
		end

	end
	def charge_card
		begin
			save!
			charge = Stripe::Charge.create(
				amount: self.amount,
				currency: "gbp",
				card: self.stripe_token,
				description: "Schedule a Call with Mentor"
				)
			self.update(stripe_id: charge.id)
			self.complete!

		rescue Stripe::StripeError => e
			self.update_attributes(error: e.message)
			self.fail!	
		end

	end

	private
		def generate_guid
			self.guid = SecureRandom.uuid()
		end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 has_many :mentors
 has_many :reviews
 has_many :reservations
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  	protect_from_forgery with: :exception

  	before_action :configure_permitted_parameters, if: :devise_controller?
	
  protected

	def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:firstname])
    devise_parameter_sanitizer.permit(:account_update, keys: [:firstname])

    devise_parameter_sanitizer.permit(:sign_up, keys: [:lastname])
    devise_parameter_sanitizer.permit(:account_update, keys: [:lastname])
  end

end

app/controllers/mentors_controller.rb
class MentorsController < ApplicationController
  before_action :set_mentor, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :check_user, only: [:edit, :update, :destroy]
  
  def index
    @mentors = Mentor.all.paginate(:page => params[:page], :per_page => 4)
  end

  def show
    if @mentor.reviews.blank?
      @average_review = 0
    else
      @average_review = @mentor.reviews.average(:rating).round(2)
    end
  end

  def new
    @mentor = current_user.mentors.build
  end

  def edit
  end

  def create
    @mentor = current_user.mentors.build(mentor_params)

    respond_to do |format|
      if @mentor.save
        format.html { redirect_to @mentor, notice: 'Mentor was successfully created.' }
        format.json { render :show, status: :created, location: @mentor }
      else
        format.html { render :new }
        format.json { render json: @mentor.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @mentor.update(mentor_params)
        format.html { redirect_to @mentor, notice: 'Mentor was successfully updated.' }
        format.json { render :show, status: :ok, location: @mentor }
      else
        format.html { render :edit }
        format.json { render json: @mentor.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @mentor.destroy
    respond_to do |format|
      format.html { redirect_to mentors_url, notice: 'Mentor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_mentor
      @mentor = Mentor.find(params[:id])
    end

    def mentor_params
      params.require(:mentor).permit(:name, :profession, :location, :price, :description, :industries, :expertise, :cover, :company)
    end

    def check_user
      if current_user != @mentor.user
        redirect_to root_url, alert: "Sorry, you don't have access to this page"
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	before_action :authenticate_user!, only: [:dashboard]
  def home
  end
  def about
  end	
  def dashboard
  	@mentor = current_user.mentors
  	@receivedcalls = Sale.where(email_mentor: current_user.email)
  	@bookedcalls = Sale.where(email_user: current_user.email)
  		
  end	
  def bementor
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

	before_action :authenticate_user!

	def create
		@reservation = current_user.reservations.create(reservation_params)

		redirect_to @reservation.mentor
	end


	private
	def reservation_params
		params.require(:reservation).permit(:start_date, :end_date, :price, :total, :mentor_id)
	end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
before_action :find_mentor
before_action :find_review, only: [:edit, :update, :destroy]
before_action :authenticate_user!, only: [:new, :edit]

	def new
		@review = Review.new
	end

	def create
		@review = Review.new(review_params)
		@review.mentor_id = @mentor.id 
		@review.user_id = current_user.id

		if @review.save
			redirect_to mentor_path(@mentor)
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @review.update(review_params)
			redirect_to mentor_path(@mentor)
		else
			render 'edit'	
		end
	end

	def destroy
		@review.destroy
		redirect_to mentor_path(@mentor)
	end

	private

		def review_params
			params.require(:review).permit(:rating, :comment)
		end

	def find_mentor
		@mentor = Mentor.find(params[:mentor_id])
	end
	
	def find_review
		@review = Review.find(params[:id])
	end

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

	def create
		mentor =  Mentor.find_by!(slug: params[:slug])

		sale = mentor.sales.create(
			amount: (mentor.price * 100).floor,
			email_user: current_user.email,
			email_mentor: mentor.user.email,
			stripe_token: params[:stripeToken]
			)
		sale.running!

		if sale.completed?
		  	redirect_to pickup_url(guid: sale.guid)
	  	else
			redirect_to mentor_path(mentor), notice: @error
		end
	end


	def pickup
		@sale = Sale.find_by!(guid: params[:guid])
		@mentor = @sale.mentor
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mentors_helper.rb
module MentorsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_footer.html.erb
<footer class="page-footer teal">
    
    <!-- <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Company Bio</h5>
          <p class="grey-text text-lighten-4">We are a team of college students working on this project like it's our full time job. Any amount would help support and continue development on this project and is greatly appreciated.</p>


        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Settings</h5>
          <ul>
            <li><a class="white-text" href="#!">Link 1</a></li>
            <li><a class="white-text" href="#!">Link 2</a></li>
            <li><a class="white-text" href="#!">Link 3</a></li>
            <li><a class="white-text" href="#!">Link 4</a></li>
          </ul>
        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Connect</h5>
          <ul>
            <li><a class="white-text" href="#!">Link 1</a></li>
            <li><a class="white-text" href="#!">Link 2</a></li>
            <li><a class="white-text" href="#!">Link 3</a></li>
            <li><a class="white-text" href="#!">Link 4</a></li>
          </ul>
        </div>
      </div>
    </div> -->

    <div class="footer-copyright">
      <div class="container">
      Made by <a class="brown-text text-lighten-3" href="">MENTORBAR</a>
      </div>
    </div>
  </footer>
            

app/views/layouts/_header.html.erb
  <nav class="white" role="navigation">
    <div class="nav-wrapper container">
    <%= link_to "MentorBar", root_path, class: "brand-logo" %>
      <ul class="right hide-on-med-and-down">
        <li><%= link_to "List of Mentors", mentors_path%></li>
	    <% if user_signed_in? %>
		    <ul id="dropdown1" class="dropdown-content">
			  <li><%= link_to "Dasboard", dashboard_path %></li>
			  <li><%= link_to "Edit Profile", edit_user_registration_path %>
			  <li class="divider"></li>
		  	  <li><%= link_to "Logout", destroy_user_session_path, method: :delete %>
			</ul>
		    <li><%= link_to "Become a Mentor", bementor_path %></li>	    	
			<li><a class="dropdown-button" href="#!" data-activates="dropdown1"><%= current_user.firstname %><i class="material-icons right">arrow_drop_down</i></a></li>
    
	    <% else %>
		    <li><%= link_to "Login", user_session_path %></li>
		    <li><%= link_to "Sign Up", new_user_registration_path %></li>
	    <% end %>
      </ul>

      <ul id="nav-mobile" class="side-nav">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "List of Mentors", mentors_path%></li>
	      <% if user_signed_in? %>
			  <li><%= link_to "Dasboard", dashboard_path %></li>
			  <li><%= link_to "Edit Profile", edit_user_registration_path %>
			  <li><%= link_to "Become a Mentor", bementor_path %></li>
			  <li class="divider"></li>
		  	  <li><%= link_to "Logout", destroy_user_session_path, method: :delete %>	    			
    
		    <% else %>
			    <li><%= link_to "Login", user_session_path %></li>
			    <li><%= link_to "Sign Up", new_user_registration_path %></li>
		    <% end %>
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MentorBar</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= csrf_meta_tags %>
   <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
   <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body>

	<%= render "layouts/header" %>
	<%= render 'pages/slider' if action_name == 'home' %>

	<main class="container">
		<div class="container">
		<% flash.each do |type, message| %>
		<script>
			Materialize.toast('<%= message %>', 4000)
		</script>
		<% end %>
		</div>
    <!-- Never remove the javascript from here -->
    <%= javascript_include_tag 'application' %>
		<%= yield %>
	</main>
	<%= render "layouts/footer" %>
</body>
</html>

app/views/mentors/_form.html.erb
<%= form_for @mentor, html: { multipart: true } do |f| %>
  <% if @mentor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mentor.errors.count, "error") %> prohibited this mentor from being saved:</h2>

      <ul>
      <% @mentor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :profession %><br>
    <%= f.text_field :profession %>
  </div>
  <div class="field">
    <%= f.label :company %><br>
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :Price_min_50_cent %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "materialize-textarea"%>
  </div>
  <div class="field">
    <%= f.label :industries %><br>
    <%= f.text_area :industries, class: "materialize-textarea" %>
  </div>
  <div class="field">
    <%= f.label :expertise %><br>
    <%= f.text_area :expertise, class: "materialize-textarea" %>
  </div>
  <div class="field">
    <label class="grey-text">Upload profile image </label>
    <%= f.file_field :cover %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit 'Become a Mentor', class: "btn btn-form"%>
    <br>
  </div>
  <br>
<% end %>

app/views/mentors/edit.html.erb
<div class="row">
	<div class="col s6 offset-l3">
		<h1>Editing Mentor</h1>

		<%= render 'form' %>

		<%= link_to 'Show', @mentor %> |
		<%= link_to 'Back', mentors_path %>
	</div>
</div>

app/views/mentors/index.html.erb
<div class="content-show">

<% @mentors.each do |mentor| %>
  <div class="row">
    <div class="col l12 s12 m12">
      <div class="col s4 waves-effect waves-block waves-light ">
        <%= image_tag mentor.cover.url(:medium), class: "img-circular-index activator" %>
      </div>
        
        <div class="col s6">
          <div>
            <span><%= mentor.name %></span>
          </div>

          <div>
            <span><%= mentor.expertise %></span>
          </div>

          <div>
            <span><%= mentor.location %></span>
          </div>

          <div>
            <span class="right"> <%= number_to_currency(mentor.price) %></span>
          </div>

          <br>
          <div>
            <span class="right"><%= link_to 'View Profile', mentor, class: "btn"%></span>
          </div>
      </div>
    </div>
  </div>
<hr class="divider-normal">
<br>
<% end %> 

  
  <br>
   <%= link_to 'New Mentor', new_mentor_path %>
  <br>
  <%= will_paginate @mentors %>

app/views/mentors/new.html.erb
<div class="row">
	<div class="col s6 offset-l3">
		<h1>New Mentor</h1>

		<%= render 'form' %>

		<%= link_to 'Back', mentors_path %>
	</div>
</div>

app/views/mentors/show.html.erb
<div class="content-show">
  <div class="row">
    <div class="col s12 l4">
      <%= image_tag @mentor.cover.url(:medium), class: "img-circular show-img"%>
      <br>
      <div class="profile-header">
          <p class="summary-positioning"> Summary</p>
      </div>
      <div class="profile-border">
        <p class="light">
          <strong>Price:</strong>
          <%= number_to_currency(@mentor.price) %>
        </p>   
          <div class="average-review-rating" data-score= <%= @average_review %>>
            <strong>Rating <span>( <%= @mentor.reviews.count %> reviews )</span>: </strong> 
          </div>
        </p>
        <%= render 'reservations/form'%>

        <span> <%= link_to 'Book a Call', mentors_path, class: "btn btn-devise"%></span>
        <br>
        <br>

        <% if current_user %>

        <%= form_tag call_path(id: @mentor.id) do %>
        <script
          src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-amount="<%= (@mentor.price * 100).floor %>"
          data-name="MentorBar"
          data-description="<%= @mentor.name %>"
          data-email="<% current_user.email %>"
          data-locale="auto"
          data-zip-code="true"
          data-currency="gbp">
        </script>
      <% end %>

      <% else %>
        <%= link_to "Login to Call", user_session_path %>
      <% end %>
      </div>
      <br>
      <div>
        <% if @mentor.user == current_user %>
          <span> <%= link_to 'Edit Profile', edit_mentor_path(@mentor), class: "btn btn-devise grey lighten-2" %></span>
          <br>
          <br>
         <%= link_to 'Destroy', @mentor, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-devise grey lighten-2"%>
        <% end %>
        <br>
        <br>
      </div>
    </div>
    <div class="col l8">
      <h3 class="light">Hey, I'm <%= @mentor.name %></h3>
      <p><strong><i class="material-icons">work</i> <%= @mentor.profession %></strong> at <%= @mentor.company %>
      <strong><i class="material-icons">location_on</i></strong>
        <%= @mentor.location %></p>
      <p class="light"><%= @mentor.description %></p>
      <br>
      <p class="light">
      <strong>Industries:</strong>
      <%= @mentor.industries %>
      </p>

      <p class="light">
      <strong>Expertise:</strong>
      <%= @mentor.expertise %>
      </p>
      <hr class="divider-normal">
      <h5> Customer Reviews</h5>

      <%= render @mentor.reviews %>
      
      <br>
      <span> <%= link_to 'Write a customer review', new_mentor_review_path(@mentor), class: "btn" %></span>
      
    </div>

   <!-- <%= link_to 'Back', mentors_path %> -->

  </div>
</div>


<script>
  $('.review-rating').raty({
      readOnly: true,
      score: function(){
        return $(this).attr('data-score');
      },
      path: '/assets/'
  })
</script>

<script>
  $('.average-review-rating').raty({
    readOnly: true,
    path: '/assets/',
    score: function() {
      return $(this).attr('data-score')
    }
  })
</script>

app/views/pages/_slider.html.erb
 <div id="index-banner" class="parallax-container">
    <div class="section no-pad-bot">
        <br><br>
        <h1 class="header center">Welcome to MentorBar</h1>
        <div class="row center">
          <h5 class="header col s12 light">Find the right mentor here</h5>
        </div>
        <div class="row center">
          <a href="http://materializecss.com/getting-started.html" id="download-button" class="btn-large waves-effect waves-light teal lighten-1">Get Started</a>
        </div>
        <br><br>
    </div>
    <div class="parallax"> <%= image_tag("/assets/image1.jpg") %></div>
</div>

app/views/pages/about.html.erb
<h1>Hellooooo About!! </h1>

app/views/pages/bementor.html.erb
<h1>Become a Mentor</h1>

app/views/pages/dashboard.html.erb
<br>

 <div class="row">
    <div class="col s12 l12">
      <ul class="tabs">
        <li class="tab col s6"><a href="#Student"><p class="dashboard-tab">Your Student Dashboard</p></a></li>
        <li class="tab col s6"><a class="active" href="#Mentor"><p class="dashboard-tab">Your Mentor Dashboard</p></a></li>
      </ul>
    </div>
    <div id="Student" class="col s12 l12">
	    <table>
	    	<thead>
				<tr>
					<th>Name</th>
					<th>Profession</th>
					<th>Price</th>
				</tr>
			</thead>
			<tbody>
				<% @bookedcalls.each do |bookedcalls| %>
					<tr>
	    				<th class="light"><%= bookedcalls.mentor.name %></th>
	    				<th class="light"><%= bookedcalls.mentor.profession %></th>
	    				<th class="light"><%= number_to_currency(bookedcalls.amount / 100) %></th>
					</tr>
				<% end %>
			</tbody>
	    </table>
    </div>


    <div id="Mentor" class="col s12 l12">
    <table>
		<thead>
			<tr>
				<th>Name</th>
				<th>Price</th>
				<th>Phone Call Length</th>
			</tr>
		</thead>
		<tbody>
			<% @receivedcalls.each do |receivedcalls| %>
				<tr>
    				<th class="light"><%= receivedcalls.email_user %></th>
    				<th class="light"><%= number_to_currency(receivedcalls.amount / 100) %></th>
    				<th class="light"> TBC </th>
				</tr>
			<% end %>
		</tbody>
    </table>
    </div>
  </div>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
  <title>MentorBar</title>

  <!-- CSS  -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="css/materialize.css" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="css/style.css" type="text/css" rel="stylesheet" media="screen,projection"/>
</head>
<body>


  <div class="section">

    <!--   Icon Section   -->
    <div class="row">
      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center brown-text"><i class="material-icons">flash_on</i></h2>
          <h5 class="center">Speeds up development</h5>

          <p class="light">We did most of the heavy lifting for you to provide a default stylings that incorporate our custom components. Additionally, we refined animations and transitions to provide a smoother experience for developers.</p>
        </div>
      </div>

      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center brown-text"><i class="material-icons">group</i></h2>
          <h5 class="center">User Experience Focused</h5>

          <p class="light">By utilizing elements and principles of Material Design, we were able to create a framework that incorporates components and animations that provide more feedback to users. Additionally, a single underlying responsive system across all platforms allow for a more unified user experience.</p>
        </div>
      </div>

      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center brown-text"><i class="material-icons">settings</i></h2>
          <h5 class="center">Easy to work with</h5>

          <p class="light">We have provided detailed documentation as well as specific code examples to help new users get started. We are also always open to feedback and can answer any questions a user may have about Materialize.</p>
        </div>
      </div>
    </div>

  </div>



  <div class="parallax-container valign-wrapper">
    <div class="section no-pad-bot">
      <div class="container">
        <div class="row center">
          <h5 class="header col s12 light">A modern responsive front-end framework based on Material Design</h5>
        </div>
      </div>
    </div>
    <div class="parallax"><img src="background2.jpg" alt="Unsplashed background img 2"></div>
  </div>


  <div class="section">

    <div class="row">
      <div class="col s12 center">
        <h3><i class="mdi-content-send brown-text"></i></h3>
        <h4>Contact Us</h4>
        <p class="left-align light">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque id nunc nec volutpat. Etiam pellentesque tristique arcu, non consequat magna fermentum ac. Cras ut ultricies eros. Maecenas eros justo, ullamcorper a sapien id, viverra ultrices eros. Morbi sem neque, posuere et pretium eget, bibendum sollicitudin lacus. Aliquam eleifend sollicitudin diam, eu mattis nisl maximus sed. Nulla imperdiet semper molestie. Morbi massa odio, condimentum sed ipsum ac, gravida ultrices erat. Nullam eget dignissim mauris, non tristique erat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>
      </div>
    </div>

  </div>



  <div class="parallax-container valign-wrapper">
    <div class="section no-pad-bot">
      <div class="row center">
        <h5 class="header col s12 light">A modern responsive front-end framework based on Material Design</h5>
      </div>
    </div>
    <div class="parallax"><img src="background3.jpg" alt="Unsplashed background img 3"></div>
  </div>

  


  <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="js/materialize.js"></script>
  <script src="js/init.js"></script>

  </body>
</html>

app/views/reservations/_form.html.erb
<%= form_for ([@mentor, @mentor.reservations.new]) do |f| %>
  <%= f.text_field :start_date, placeholder: 'Enter start date' %>
  <%= f.text_field :end_date, placeholder: 'Enter end date' %>
  <%= f.hidden_field :mentor_id, value: @mentor.id %>
  <%= f.hidden_field :price, value: @mentor.price %>
  <div id="finalPrice">0</div>
  <br>
  <%= f.submit "Book Now", class: "btn" %>
<% end %>

app/views/reviews/_form.html.erb
<%= simple_form_for([@mentor, @mentor.reviews.build]) do |f| %>
	<div id="rating-form">
		<label>Rating</label>
	</div>
	<%= f.input :comment %>
	<%= f.button :submit %>
<% end %>

<script>
$('#rating-form').raty({
	path: '/assets/',
	scoreName: 'review[rating]'
});
</script>

app/views/reviews/_review.html.erb
<p><div class="review-rating" data-score="<%= review.rating %>"></div>
<%= review.comment %></p>

<% if user_signed_in? %>
	<% if review.user_id == current_user.id %>

		<%= link_to "Edit", edit_mentor_review_path(review.mentor, review) %>
		<%= link_to "Delete", mentor_review_path(review.mentor, review), method: :delete, data: {confirm: "Are you sure you want to delete your review?" } %>
	<% end %>
<% end %>

app/views/reviews/edit.html.erb
<h1>hello edit review</h1>
 
<%= simple_form_for([@mentor, @review]) do |f| %>
<div id="rating-form">
	<label>Rating</label>
</div>
<%= f.input :comment %>
<%= f.button :submit %>
<% end %>

<script>
$('#rating-form').raty({
	path: '/assets/',
	scoreName: 'review[rating]'
});
</script>

app/views/reviews/new.html.erb
<h1> New Review</h1>
 <%= render 'form' %>

app/views/transactions/pickup.html.erb
<h1> Thanks for Booking a call! </h1>